### ISSUE TITLE
升级测试3.0.0升级到3.0.9不能绑定uid，返回null

### ISSUE THREAD

**Issue by wenrouzei** [walkor/GatewayClient#10]
升级测试3.0.0升级到3.0.9使用Gateway::bindUid()不能绑定uid，返回null

**Comment by walkor** [comment]
gatewayWorker 版本是？

**Comment by wenrouzei** [comment]
gateway-worker:3.0.7、3.0.9都测试过返回null

**Comment by walkor** [comment]
根据手册，这个返回就是null

**Comment by wenrouzei** [comment]
我再测试了下3.0.0版本是返回true，而3.0.9版本是返回null（但是有绑定成功了），只是之前的判断逻辑要改下，看源码是取消了return，这个没绑定成功会抛出错误么，怎么判断绑定状态呢

**Comment by walkor** [comment]
异步的接口，没办法判断是否成功

**Comment by li914** [comment]
绑定后，使用Gateway:isUidOnline(uid) 来判断，如果绑定成功了会返回1.
