### ISSUE TITLE
Fatal error: in ../../Gateway.php on line 1286

### ISSUE THREAD

**Issue by SimonSUSU** [walkor/GatewayClient#13]
Fatal error: in ../../Gateway.php on line 1286
Gateway.php当无法连接SETCKET时，代码会报错，没有做异常处理。

**Comment by walkor** [comment]
具体报错是？

**Comment by SimonSUSU** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Walkor:非常感谢你的回复。报错的原因是当无法联接到服务端时，代码报错。没有做异常处理。  建议加个异步处理。避免业务系统因为这个无法运行。Fatal error: in ...\Gateway.php on line 1286by simon
    
        
        

        
    

    On 10/30/2018 11:19，walkor<notifications@github.com> wrote： 


具体报错是？

**Comment by walkor** [comment]
你看下报错那段代码是什么？这里线上版本看到1286行不会有报错。
如果连不上服务器Gateway.php里面是故意抛异常的，目的是为了让开发者了解哪里出了问题，如果业务不关心报错想继续执行可以在调用Gateway接口的地方try catch下
