### ISSUE TITLE
GatewayWorker 使用的是3.0.12版本 PHP 5.6.31  安装时报如下错误： composer require workerman/gatewayclient

### ISSUE THREAD

**Issue by kl521516** [walkor/GatewayClient#16]
GatewayWorker 使用的是3.0.12版本
PHP 5.6.31

安装时报如下错误：
composer require workerman/gatewayclient

Zend Guard Loader requires Zend Engine API version 220090626.
The Zend Engine API version 220131226 which is installed, is newer.
Contact Zend Technologies at http://www.zend.com/ for a later version of Zend Guard Loader.

Using version ^3.0 for workerman/gatewayclient
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.6.31) does not satisfy that requirement.
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.6.31) does not satisfy that requirement.
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.6.31) does not satisfy that requirement.
    - Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].

Installation failed, reverting ./composer.json to its original content.

**Comment by walkor** [comment]
这个不是gatewayClient的问题，看起来是paragonie/random_compat要求php>=7，但是你的php版本是5.6。gatewayClient没有这个要求，并且也不依赖paragonie/random_compat
