### ISSUE TITLE
請問這範例中的$_SESSION是php本身的session嗎?

### ISSUE THREAD

**Issue by esliupm** [walkor/GatewayClient#5]
<?php 
//bind.php
//加载GatewayClient。安装GatewayClient参见本页面底部介绍
require_once '/your/path/GatewayClient/Gateway.php';
// GatewayClient 3.0.0版本开始要使用命名空间
use GatewayClient\Gateway;
// 设置GatewayWorker服务的Register服务ip和端口，请根据实际情况改成实际值
Gateway::$registerAddress = '127.0.0.1:1236';

// 假设用户已经登录，用户uid和群组id在session中
$uid      = $_SESSION['uid'];
$group_id = $_SESSION['group'];
// client_id与uid绑定
Gateway::bindUid($client_id, $uid);
// 加入某个群组（可调用多次加入多个群组）
Gateway::joinGroup($client_id, $group_id);

=================================
問題2
bind.php 內我加上
$clients_list = Gateway::getClientSessionsByGroup($_POST["room_id"]);
                foreach($clients_list as $tmp_client_id=>$item)
                {
                    $clients_list[$tmp_client_id] = $item['client_name'];
                }
但是$item['client_name'] 會是 null,這是什麼原因呢??

**Comment by walkor** [comment]
抱歉，看不到你的说的范例是什么。
代码看起来样式有问题，请使用github的编辑器把代码整理好。
感谢

**Comment by esliupm** [comment]
//bind.php
//加载GatewayClient。安装GatewayClient参见本页面底部介绍
require_once '/your/path/GatewayClient/Gateway.php';
// GatewayClient 3.0.0版本开始要使用命名空间
use GatewayClient\Gateway;
// 设置GatewayWorker服务的Register服务ip和端口，请根据实际情况改成实际值
Gateway::$registerAddress = '127.0.0.1:1236';

// 假设用户已经登录，用户uid和群组id在session中
$uid      = $_SESSION['uid'];
$group_id = $_SESSION['group'];
// client_id与uid绑定
Gateway::bindUid($client_id, $uid);
// 加入某个群组（可调用多次加入多个群组）
Gateway::joinGroup($client_id, $group_id);

=================================
問題2
bind.php 內我加上
$clients_list = Gateway::getClientSessionsByGroup($_POST["room_id"]);
                foreach($clients_list as $tmp_client_id=>$item)
                {
                    $clients_list[$tmp_client_id] = $item['client_name'];
                }
但是$item['client_name'] 會是 null,這是什麼原因呢??

**Comment by walkor** [comment]
例子中的$_SESSION是php的session，但是Gateway的session不是php自带的session。

Gateway的session需要用Gateway::setSessions Gateway::setSession给client_id设置session
