### ISSUE TITLE
建议把 self::$registerAddress 改成  static::$registerAddress 

### ISSUE THREAD

**Issue by big-sponge** [walkor/GatewayClient#8]
建议把 self::$registerAddress 改成  static::$registerAddress 
这样我新建一个类，继承Gateway后， 就可以覆盖里面的配置了

**Comment by big-sponge** [comment]
或者用个单例，方便修改配置。目前每次使用时候都需要指定一下地址

**Comment by walkor** [comment]
主干已经更改
