### ISSUE TITLE
关于Gateway类中的secretKey 说明

### ISSUE THREAD

**Issue by bangbangce** [walkor/GatewayClient#9]
/**
     * gateway 实例
     *
     * @var object
     */
    protected static $businessWorker = null;

    /**
     * 注册中心地址
     *
     * @var string
     */
    public static $registerAddress = '127.0.0.1:1236';

    /**
     * 秘钥
     * @var string
     */
    public static $secretKey = '';

    /**
     * 链接超时时间
     * @var int
     */
    public static $connectTimeout = 3;

请问以上配置中的secretKey是取什么秘钥？是不是gateway配置中的keypath？

**Comment by bangbangce** [comment]
补充一下，上面提到的keypath 是指证书路径

**Comment by walkor** [comment]
secretKey是预留的属性，目前没用到，和证书没关系
